Remove more unused versions

diff --git a/.github/workflows/publish-node.yml b/.github/workflows/publish-node.yml
--- a/.github/workflows/publish-node.yml
+++ b/.github/workflows/publish-node.yml
@@ -253,45 +253,45 @@ jobs:
         run: yarn build:ts
       - name: Test bindings
         run: yarn test
-  test-linux-x64-gnu-binding:
-    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
-    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          # - "14"
-          # - "16"
-          - "18"
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Setup node
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.node }}
-          check-latest: true
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: npm-cache-test-linux-x64-gnu-${{ matrix.node }}
-      - name: Install dependencies
-        run: yarn install --ignore-scripts --registry https://registry.npmjs.org --network-timeout 300000
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-x86_64-unknown-linux-gnu
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Build TypeScript
-        run: yarn build:ts
-      - name: Test bindings
-        run: docker run --rm -v $(pwd):/swc -w /swc node:${{ matrix.node }}-slim env DISABLE_PLUGIN_E2E_TESTS=true yarn test
+  # test-linux-x64-gnu-binding:
+  #   if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
+  #   name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
+  #   needs:
+  #     - build
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node:
+  #         # - "14"
+  #         # - "16"
+  #         - "18"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Setup node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: ${{ matrix.node }}
+  #         check-latest: true
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: node_modules
+  #         key: npm-cache-test-linux-x64-gnu-${{ matrix.node }}
+  #     - name: Install dependencies
+  #       run: yarn install --ignore-scripts --registry https://registry.npmjs.org --network-timeout 300000
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: bindings-x86_64-unknown-linux-gnu
+  #         path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
+  #     - name: Build TypeScript
+  #       run: yarn build:ts
+  #     - name: Test bindings
+  #       run: docker run --rm -v $(pwd):/swc -w /swc node:${{ matrix.node }}-slim env DISABLE_PLUGIN_E2E_TESTS=true yarn test
   test-linux-x64-musl-binding:
     if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
     name: Test bindings on x86_64-unknown-linux-musl - node@${{ matrix.node }}
@@ -331,83 +331,83 @@ jobs:
         run: yarn build:ts
       - name: Test bindings
         run: docker run --rm -v $(pwd):/swc -w /swc node:${{ matrix.node }}-alpine env DISABLE_PLUGIN_E2E_TESTS=true yarn test
-  test-linux-aarch64-musl-binding:
-    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
-    name: Test bindings on aarch64-unknown-linux-musl - node@${{ matrix.node }}
-    needs:
-      - build
-    runs-on: ubuntu-latest
-    steps:
-      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
-      - uses: actions/checkout@v3
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-aarch64-unknown-linux-musl
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: npm-cache-test-linux-aarch64-musl-${{ matrix.node }}
-      - name: Install dependencies
-        run: yarn install --ignore-scripts --ignore-platform --registry https://registry.npmjs.org --network-timeout 300000
-      - name: Build TypeScript
-        run: yarn build:ts
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: multiarch/alpine:aarch64-latest-stable
-          options: "-v ${{ github.workspace }}:/build -w /build"
-          run: |
-            set -e
-            apk add nodejs npm yarn
-            DISABLE_PLUGIN_E2E_TESTS=true yarn test
-  test-linux-arm-gnueabihf-binding:
-    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
-    name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          # - "14"
-          # - "16"
-          - "18"
-    runs-on: ubuntu-latest
-    steps:
-      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
-      - uses: actions/checkout@v3
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-armv7-unknown-linux-gnueabihf
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: node_modules
-          key: npm-cache-test-linux-arm-gnueabihf-${{ matrix.node }}
-      - name: Install dependencies
-        run: yarn install --ignore-scripts --ignore-platform --registry https://registry.npmjs.org --network-timeout 300000
-      - name: Build TypeScript
-        run: yarn build:ts
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/napi-rs/napi-rs/nodejs:armhf-${{ matrix.node }}
-          options: "-v ${{ github.workspace }}:/build -w /build"
-          run: |
-            set -e
-            DISABLE_PLUGIN_E2E_TESTS=true yarn test
-            ls -la
+  # test-linux-aarch64-musl-binding:
+  #   if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
+  #   name: Test bindings on aarch64-unknown-linux-musl - node@${{ matrix.node }}
+  #   needs:
+  #     - build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
+  #     - uses: actions/checkout@v3
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: bindings-aarch64-unknown-linux-musl
+  #         path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: node_modules
+  #         key: npm-cache-test-linux-aarch64-musl-${{ matrix.node }}
+  #     - name: Install dependencies
+  #       run: yarn install --ignore-scripts --ignore-platform --registry https://registry.npmjs.org --network-timeout 300000
+  #     - name: Build TypeScript
+  #       run: yarn build:ts
+  #     - name: Setup and run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: multiarch/alpine:aarch64-latest-stable
+  #         options: "-v ${{ github.workspace }}:/build -w /build"
+  #         run: |
+  #           set -e
+  #           apk add nodejs npm yarn
+  #           DISABLE_PLUGIN_E2E_TESTS=true yarn test
+  # test-linux-arm-gnueabihf-binding:
+  #   if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/fork' }}
+  #   name: Test bindings on armv7-unknown-linux-gnueabihf - node@${{ matrix.node }}
+  #   needs:
+  #     - build
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       node:
+  #         # - "14"
+  #         # - "16"
+  #         - "18"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
+  #     - uses: actions/checkout@v3
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: bindings-armv7-unknown-linux-gnueabihf
+  #         path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
+  #     - name: Cache NPM dependencies
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: node_modules
+  #         key: npm-cache-test-linux-arm-gnueabihf-${{ matrix.node }}
+  #     - name: Install dependencies
+  #       run: yarn install --ignore-scripts --ignore-platform --registry https://registry.npmjs.org --network-timeout 300000
+  #     - name: Build TypeScript
+  #       run: yarn build:ts
+  #     - name: Setup and run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: ghcr.io/napi-rs/napi-rs/nodejs:armhf-${{ matrix.node }}
+  #         options: "-v ${{ github.workspace }}:/build -w /build"
+  #         run: |
+  #           set -e
+  #           DISABLE_PLUGIN_E2E_TESTS=true yarn test
+  #           ls -la
   publish:
     if: ${{ startsWith(github.ref, 'refs/tags/v') }}
 
